### ISSUE TITLE
Feature: Add documentation for PATCH-ing Members

### ISSUE THREAD

**Issue by WinterPhoenix** [Patreon/platform-documentation#60]
There's no documentation on how to update members, for example adding a Creator Note (`member.note`) programmatically. I had to discover the method using Browser Dev Tools from my Creator Dashboard.

Come on guys, you run the most popular membership platform in the world. This sort of friction is what causes new creators interested in tight app integration, like myself, to skip Patreon entirely.

**Comment by codebard** [comment]
The public API does not support write operations. Using Patreon's internal APIs with your own user tokens for patreon.com is also not supported.
